name: Clean NonProfit Data and Load to Staging Schema

on:
  schedule:
    - cron: '0 2 1 * *'  # Run at 2:00 AM UTC on the 1st of every month
  workflow_dispatch:      # optional manual trigger

env:
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_DB: ${{ secrets.PG_DB }}

jobs:
  cleaning_staging_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run API Cleaning Script
      run: python notebooks/nonprofit_api_clean_staging.py

    - name: Run Web Scrape Cleaning Script
      run: python notebooks/nonprofit_webscrape_clean_staging.py